import type { Metadata } from "next";

import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import NextTopLoader from "nextjs-toploader";
import Providers from "@/lib/Providers";

export const metadata: Metadata = {
  title: "Task-Management-Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <ClerkProvider>
        <html lang="en">
          <body>
            <NextTopLoader
              height={2}
              color="#27AE60"
              easing="cubic-bezier(0.53,0.21,0,1)"
              showSpinner={false}
            />
            {children}
          </body>
        </html>
      </ClerkProvider>
    </Providers>
  );
}
